export type Material = {
  autoImportQuantity: number;
  id: string;
  materialId: string;
  materialCode: string;
  materialName: string;
  materialImage: string;
  variantId: string | null;
  variantName: string | null;
  variantImage: string | null;
  brand: string;
  weight: number;
  parentCategory: string;
  category: string;
  unit: string;
  supplier: string;
  quantity: number;
  minStock: number;
  maxStock: number;
  materialPrice: number;
  materialCostPrice: number | null;
  variantPrice: number | null;
  variantCostPrice: number | null;
  discount: number | null;
  afterDiscountPrice: number | null;
  attributes: IAttributes[];
  lastUpdateTime: string;
};
export type IAttributes = {
  name: string;
  value: string;
};
