import { Roboto } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";
import { QueryProvider } from "@/providers/query-provider";
import { Toaster } from "@/components/ui/toaster";
import SessionProviders from "@/providers/session-provider";
import NextTopLoader from "nextjs-toploader";
import { RoleProvider } from "@/providers/role-context";
const roboto = Roboto({ weight: "400", subsets: ["vietnamese"] });

export const metadata: Metadata = {
  title: "CMMS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} antialiased`}>
        <NextTopLoader height={5} />
        <SessionProviders>
          <RoleProvider>
            <QueryProvider>
              {children}
              <Toaster />
            </QueryProvider>
          </RoleProvider>
        </SessionProviders>
      </body>
    </html>
  );
}
